spring.application.name=backend

# Load environment variables from root .env file
spring.config.import=optional:file:../.env[.properties]

# Supabase
supabase.url=${SUPABASE_URL}
supabase.publishable-key=${SUPABASE_PUBLISHABLE_KEY}
supabase.secret-key=${SUPABASE_SECRET_KEY}